//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SARSCOV2.ModelsDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<miasta> miasta { get; set; }
        public virtual DbSet<pow_source> pow_source { get; set; }
        public virtual DbSet<pow_target> pow_target { get; set; }
        public virtual DbSet<woj_source> woj_source { get; set; }
        public virtual DbSet<woj_target> woj_target { get; set; }
        public virtual DbSet<wojewodztwa> wojewodztwa { get; set; }
        public virtual DbSet<woj_targetView> woj_targetView { get; set; }
    
        public virtual ObjectResult<woj_filter_records_Result> woj_filter_records(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, string wojewodztwo)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("Fromdate", fromdate) :
                new ObjectParameter("Fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("Todate", todate) :
                new ObjectParameter("Todate", typeof(System.DateTime));
    
            var wojewodztwoParameter = wojewodztwo != null ?
                new ObjectParameter("wojewodztwo", wojewodztwo) :
                new ObjectParameter("wojewodztwo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<woj_filter_records_Result>("woj_filter_records", fromdateParameter, todateParameter, wojewodztwoParameter);
        }
    
        public virtual ObjectResult<woj_target> function_woj_filter_records(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, string wojewodztwo)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("Fromdate", fromdate) :
                new ObjectParameter("Fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("Todate", todate) :
                new ObjectParameter("Todate", typeof(System.DateTime));
    
            var wojewodztwoParameter = wojewodztwo != null ?
                new ObjectParameter("wojewodztwo", wojewodztwo) :
                new ObjectParameter("wojewodztwo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<woj_target>("function_woj_filter_records", fromdateParameter, todateParameter, wojewodztwoParameter);
        }
    
        public virtual ObjectResult<woj_target> function_woj_filter_records(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, string wojewodztwo, MergeOption mergeOption)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("Fromdate", fromdate) :
                new ObjectParameter("Fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("Todate", todate) :
                new ObjectParameter("Todate", typeof(System.DateTime));
    
            var wojewodztwoParameter = wojewodztwo != null ?
                new ObjectParameter("wojewodztwo", wojewodztwo) :
                new ObjectParameter("wojewodztwo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<woj_target>("function_woj_filter_records", mergeOption, fromdateParameter, todateParameter, wojewodztwoParameter);
        }
    
        public virtual ObjectResult<pow_filter_records_Result> pow_filter_records(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, string powiat_miasto)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("Fromdate", fromdate) :
                new ObjectParameter("Fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("Todate", todate) :
                new ObjectParameter("Todate", typeof(System.DateTime));
    
            var powiat_miastoParameter = powiat_miasto != null ?
                new ObjectParameter("powiat_miasto", powiat_miasto) :
                new ObjectParameter("powiat_miasto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pow_filter_records_Result>("pow_filter_records", fromdateParameter, todateParameter, powiat_miastoParameter);
        }
    
        public virtual ObjectResult<pow_target> function_pow_filter_records(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, string powiat_miasto)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("Fromdate", fromdate) :
                new ObjectParameter("Fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("Todate", todate) :
                new ObjectParameter("Todate", typeof(System.DateTime));
    
            var powiat_miastoParameter = powiat_miasto != null ?
                new ObjectParameter("powiat_miasto", powiat_miasto) :
                new ObjectParameter("powiat_miasto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pow_target>("function_pow_filter_records", fromdateParameter, todateParameter, powiat_miastoParameter);
        }
    
        public virtual ObjectResult<pow_target> function_pow_filter_records(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, string powiat_miasto, MergeOption mergeOption)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("Fromdate", fromdate) :
                new ObjectParameter("Fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("Todate", todate) :
                new ObjectParameter("Todate", typeof(System.DateTime));
    
            var powiat_miastoParameter = powiat_miasto != null ?
                new ObjectParameter("powiat_miasto", powiat_miasto) :
                new ObjectParameter("powiat_miasto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pow_target>("function_pow_filter_records", mergeOption, fromdateParameter, todateParameter, powiat_miastoParameter);
        }
    
        public virtual ObjectResult<woj_filter_raport_Result> woj_filter_raport(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, string wojewodztwo)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("Fromdate", fromdate) :
                new ObjectParameter("Fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("Todate", todate) :
                new ObjectParameter("Todate", typeof(System.DateTime));
    
            var wojewodztwoParameter = wojewodztwo != null ?
                new ObjectParameter("wojewodztwo", wojewodztwo) :
                new ObjectParameter("wojewodztwo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<woj_filter_raport_Result>("woj_filter_raport", fromdateParameter, todateParameter, wojewodztwoParameter);
        }
    
        public virtual ObjectResult<woj_filter_raport1_Result> woj_filter_raport1(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, string wojewodztwo)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("Fromdate", fromdate) :
                new ObjectParameter("Fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("Todate", todate) :
                new ObjectParameter("Todate", typeof(System.DateTime));
    
            var wojewodztwoParameter = wojewodztwo != null ?
                new ObjectParameter("wojewodztwo", wojewodztwo) :
                new ObjectParameter("wojewodztwo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<woj_filter_raport1_Result>("woj_filter_raport1", fromdateParameter, todateParameter, wojewodztwoParameter);
        }
    }
}
