//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SARSCOV2.ModelsDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<miasta> miasta { get; set; }
        public virtual DbSet<pow_source> pow_source { get; set; }
        public virtual DbSet<pow_target> pow_target { get; set; }
        public virtual DbSet<woj_source> woj_source { get; set; }
        public virtual DbSet<woj_target> woj_target { get; set; }
        public virtual DbSet<wojewodztwa> wojewodztwa { get; set; }
    }
}
