//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SARSCOV2.ModelsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class miasta
    {
        public int id { get; set; }
        public string miasto { get; set; }
        public Nullable<int> populacja { get; set; }
    }
}
